# **Estatística Básica com Python**

Profa. Amanda Buosi Gazon Milani - IME/UFG - amandamilani@ufg.br


# **Importando bibliotecas**

In [1]:
import pandas as pd
import numpy as np
import math

# **Breve introdução à linguagem Python**

## Operações básicas


In [2]:
print('Bem-vindos(as) à aula de introdução à linguagem de programação Python')

Bem-vindos(as) à aula de introdução à linguagem de programação Python


In [3]:
# soma:
2+2

4

In [4]:
# subtração:
2-5

-3

In [5]:
# multiplicação:
2*7

14

In [6]:
# divisão:
10/5

2.0

In [7]:
# resto da divisão:
10 % 3

1

In [8]:
# valor absoluto:
abs(-3)

3

In [9]:
# potência:
3**2

9

In [10]:
# raiz quadrada:
16**(1/2)

4.0

In [11]:
# raiz quadrada:
math.sqrt(16)

4.0

In [12]:
# arredondar:
round(0.666666, 2)

0.67

In [13]:
# arredondar:
round(0.33333, 2)

0.33

In [14]:
# arredondar - truncar:
math.trunc(4.66662)

4

In [15]:
# arredondar - menor inteiro mais próximo:
math.floor(4.6666)


4

In [16]:
# arredondar - maior inteiro mais próximo:
math.ceil(4.333)

5

## Operadores lógicos


In [17]:
# Verdadeiro:
a = True

In [18]:
# Falso:
b = False

In [19]:
# operador lógico "e" (opção 1):
a and b

False

In [20]:
# operador lógico "e" (opção 2):
a & b

False

In [21]:
# operador lógico "ou" (opção 1):
a or b

True

In [22]:
# operador lógico "ou" (opção 2):
a | b

True

In [23]:
# Verifica se maior:
5 > 3

True

In [24]:
# Verifica se menor:
5 < 3

False

In [25]:
# Verifica se maior ou igual:
5 >= 5

True

In [26]:
# Verifica se menor ou igual:
5 <= 3

False

In [27]:
# Verifica se igual:
5 == 3

False

In [28]:
# Verifica se diferente:
5 != 3

True

## Operadores condicionais

*   **if / else**




In [29]:
if 5 > 4:
  print('5 é maior')
else:
  print('5 não é maior')

5 é maior


In [30]:
n = 8
if n == 4:
  print('n é igual a 4')
else:
  if n == 3:
    print('n é igual a 3')
  else:
    print('n não é igual a 4 nem 3')

n não é igual a 4 nem 3


Importante! No Python, é necessária a correta identação.

## Estruturas de repetição

*   **for**

In [31]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [32]:
list(range(1, 6))

[1, 2, 3, 4, 5]

In [33]:
soma = 0
for numero in range(1, 6):
  soma = soma + numero
  print(soma)

#print(soma)

1
3
6
10
15


In [34]:
soma = 0
for numero in range(1, 6):
  soma = soma + numero
  #print(soma)

print(soma)

15


*   **while**

In [35]:
numero = 1
while numero < 6:
  print(numero)
  numero += 1
#print('---')

1
2
3
4
5


In [36]:
numero = 1
while numero < 6:
  print(numero)
  numero += 1
print('---')

1
2
3
4
5
---


In [37]:
numero = 1
while numero < 6:
  print(numero)
  numero += 1
  print('---')

1
---
2
---
3
---
4
---
5
---


## Vetores, Matrizes e Arrays

*   **Vetor**




In [38]:
vetor = np.array([1,2,3])

In [39]:
vetor

array([1, 2, 3])

In [40]:
print(vetor)

[1 2 3]


In [41]:
vetor.shape

(3,)

In [42]:
vetor.size

3

In [43]:
vetor[0]

np.int64(1)

In [44]:
vetor[2]

np.int64(3)

In [45]:
np.repeat(3, 4)

array([3, 3, 3, 3])

In [46]:
np.repeat([1,2,3], 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [47]:
np.repeat([1,2,3], [3,2,7])

array([1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 3])

In [48]:
np.repeat([[1,2,3]], 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [49]:
np.repeat([[1,2,3]], 4, axis=1)

array([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])

In [50]:
np.repeat([[1,2,3]], 4, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [51]:
(np.repeat([[1,2,3]], 4, axis=0)).reshape(12,)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

*   **Matriz**

In [52]:
matriz = np.array([[1, 2, 3],
                   [2, 4, 6]])

In [53]:
matriz

array([[1, 2, 3],
       [2, 4, 6]])

In [54]:
print(matriz)

[[1 2 3]
 [2 4 6]]


In [55]:
matriz.shape

(2, 3)

In [56]:
matriz[0]

array([1, 2, 3])

In [57]:
matriz[0,:]

array([1, 2, 3])

In [58]:
matriz[:,1]

array([2, 4])

In [59]:
matriz[0,2]

np.int64(3)

In [60]:
matriz[1,2]

np.int64(6)

*   **Array**

In [61]:
cubo = np.array([[[1,2,3],[4,5,6]],
                 [[2,4,6],[8,10,12]],
                 [[3,6,9],[12,15,18]]])

In [62]:
cubo

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 3,  6,  9],
        [12, 15, 18]]])

In [63]:
cubo[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
cubo[0,1]

array([4, 5, 6])

In [65]:
cubo[0,1,1]

np.int64(5)

In [66]:
v = np.array(range(10)).reshape(2,5)
v

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
v2 = np.array(range(30)).reshape(2,5,3)
v2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

*   **Matrizes especiais**

In [68]:
# matriz de zeros:
matriz_zeros = np.zeros((3,3))
matriz_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
# matriz de uns:
matriz_uns = np.ones((3,3))
matriz_uns

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
# matriz diagonal:
matriz_diag = np.diag([10, 20, 30])
matriz_diag

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [71]:
# inversa de uma matriz quadrada:
np.linalg.inv(matriz_diag)

array([[0.1       , 0.        , 0.        ],
       [0.        , 0.05      , 0.        ],
       [0.        , 0.        , 0.03333333]])

In [72]:
matriz

array([[1, 2, 3],
       [2, 4, 6]])

In [73]:
# transposta de uma matriz:
matriz.transpose()

array([[1, 2],
       [2, 4],
       [3, 6]])

# **Exercícios**

**1)** Leia a idade do usuário e classifique-o em:

Criança – 0 a 12 anos

Adolescente – 13 a 17 anos

Adulto – acima de 18 anos

-Se o usuário digitar um número negativo, mostrar a mensagem que a idade é inválida.

**2)** Construa uma matriz diagonal de dimensão 5x5, cujos elementos da diagonal principal são todos iguais a 100.

**3)** Construa uma operação lógica que verifica se um número inteiro é par ou ímpar.

**4)** Imprimir a tabuada do número 3 (3 x 0 = 0 até 3 x 10 = 30) usando a estrutura de repetição ***for***.

**5)** Imprimir a tabuada do número 3 (3 x 1 = 3 até 3 x 10 = 30) usando a estrutura de repetição ***while***.

# **Importando bases de dados**

### **Usando biblioteca de conjuntos de dados**

In [74]:
pip install pydataset

     ---------------------------------------- 0.0/15.9 MB ? eta -:--:--
      --------------------------------------- 0.3/15.9 MB ? eta -:--:--
     --- ------------------------------------ 1.3/15.9 MB 4.0 MB/s eta 0:00:04
     ----- ---------------------------------- 2.1/15.9 MB 4.3 MB/s eta 0:00:04
     ------- -------------------------------- 2.9/15.9 MB 3.9 MB/s eta 0:00:04
     ------- -------------------------------- 3.1/15.9 MB 3.9 MB/s eta 0:00:04
     ------- -------------------------------- 3.1/15.9 MB 3.9 MB/s eta 0:00:04
     ------- -------------------------------- 3.1/15.9 MB 3.9 MB/s eta 0:00:04
     ------- -------------------------------- 3.1/15.9 MB 3.9 MB/s eta 0:00:04
     ------- -------------------------------- 3.1/15.9 MB 3.9 MB/s eta 0:00:04
     ------- -------------------------------- 3.1/15.9 MB 3.9 MB/s eta 0:00:04
     ------- -------------------------------- 3.1/15.9 MB 3.9 MB/s eta 0:00:04
     ------- -------------------------------- 3.1/15.9 MB 3.9 MB/s


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [75]:
from pydataset import data

initiated datasets repo at: C:\Users\Wagner\.pydataset/


In [76]:
data()

dataset_id                                             title
0    AirPassengers       Monthly Airline Passenger Numbers 1949-1960
1          BJsales                 Sales Data with Leading Indicator
2              BOD                         Biochemical Oxygen Demand
3     Formaldehyde                     Determination of Formaldehyde
4     HairEyeColor         Hair and Eye Color of Statistics Students
..             ...                                               ...
752        VerbAgg                  Verbal Aggression item responses
753           cake                 Breakage Angle of Chocolate Cakes
754           cbpp                 Contagious bovine pleuropneumonia
755    grouseticks  Data on red grouse ticks from Elston et al. 2001
756     sleepstudy       Reaction times in a sleep deprivation study

[757 rows x 2 columns]

In [77]:
# Exibir o dataset 'mtcars'
data('mtcars')

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
Mazda RX4            21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag        21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710           22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive       21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout    18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
Valiant              18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
Duster 360           14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   
Merc 240D            24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
Merc 230             22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   
Merc 280             19.2    6  167.6  123  3.92  3.440  18.30   1   0     4   
Merc 280C            17.8    6  167.6  123  3.92  3.440  18.90   1   0     4   
Merc 450SE           16.4    8  275.8  180  3.07  4.070  17.40   0   0     3   
Merc 450SL           17.3    8  275.8  180  3.07  3.730  17.60   0   0     3   
Merc 450SLC          15.2    8  275.8  180  3.07  3.780  18.00   0   0     3   
Cadillac Fleetwood   10.4    8  472.0  205  2.93  5.250  17.98   0   0     3   
Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3   
Chrysler Imperial    14.7    8  440.0  230  3.23  5.345  17.42   0   0     3   
Fiat 128             32.4    4   78.7   66  4.08  2.200  19.47   1   1     4   
Honda Civic          30.4    4   75.7   52  4.93  1.615  18.52   1   1     4   
Toyota Corolla       33.9    4   71.1   65  4.22  1.835  19.90   1   1     4   
Toyota Corona        21.5    4  120.1   97  3.70  2.465  20.01   1   0     3   
Dodge Challenger     15.5    8  318.0  150  2.76  3.520  16.87   0   0     3   
AMC Javelin          15.2    8  304.0  150  3.15  3.435  17.30   0   0     3   
Camaro Z28           13.3    8  350.0  245  3.73  3.840  15.41   0   0     3   
Pontiac Firebird     19.2    8  400.0  175  3.08  3.845  17.05   0   0     3   
Fiat X1-9            27.3    4   79.0   66  4.08  1.935  18.90   1   1     4   
Porsche 914-2        26.0    4  120.3   91  4.43  2.140  16.70   0   1     5   
Lotus Europa         30.4    4   95.1  113  3.77  1.513  16.90   1   1     5   
Ford Pantera L       15.8    8  351.0  264  4.22  3.170  14.50   0   1     5   
Ferrari Dino         19.7    6  145.0  175  3.62  2.770  15.50   0   1     5   
Maserati Bora        15.0    8  301.0  335  3.54  3.570  14.60   0   1     5   
Volvo 142E           21.4    4  121.0  109  4.11  2.780  18.60   1   1     4   

                     carb  
Mazda RX4               4  
Mazda RX4 Wag           4  
Datsun 710              1  
Hornet 4 Drive          1  
Hornet Sportabout       2  
Valiant                 1  
Duster 360              4  
Merc 240D               2  
Merc 230                2  
Merc 280                4  
Merc 280C               4  
Merc 450SE              3  
Merc 450SL              3  
Merc 450SLC             3  
Cadillac Fleetwood      4  
Lincoln Continental     4  
Chrysler Imperial       4  
Fiat 128                1  
Honda Civic             2  
Toyota Corolla          1  
Toyota Corona           1  
Dodge Challenger        2  
AMC Javelin             2  
Camaro Z28              4  
Pontiac Firebird        2  
Fiat X1-9               1  
Porsche 914-2           2  
Lotus Europa            2  
Ford Pantera L          4  
Ferrari Dino            6  
Maserati Bora           8  
Volvo 142E              2

In [78]:
# Exibir o dataset 'mtcars' e sua documentação
data('mtcars', show_doc=True)

mtcars

PyDataset Documentation (adopted from R Documentation. The displayed examples are in R)

## Motor Trend Car Road Tests

### Description

The data was extracted from the 1974 _Motor Trend_ US magazine, and comprises
fuel consumption and 10 aspects of automobile design and performance for 32
automobiles (1973–74 models).

### Usage

    mtcars

### Format

A data frame with 32 observations on 11 variables.

[, 1]

mpg

Miles/(US) gallon

[, 2]

cyl

Number of cylinders

[, 3]

disp

Displacement (cu.in.)

[, 4]

hp

Gross horsepower

[, 5]

drat

Rear axle ratio

[, 6]

wt

Weight (lb/1000)

[, 7]

qsec

1/4 mile time

[, 8]

vs

V/S

[, 9]

am

Transmission (0 = automatic, 1 = manual)

[,10]

gear

Number of forward gears

[,11]

carb

Number of carburetors

### Source

Henderson and Velleman (1981), Building multiple regression models
interactively. _Biometrics_, **37**, 391–411.

### Examples

    require(graphics)
    pairs(mtcars, main = "mtcars data")
    coplot(mpg ~ disp 

In [79]:
data('iris')

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
1             5.1          3.5           1.4          0.2      setosa
2             4.9          3.0           1.4          0.2      setosa
3             4.7          3.2           1.3          0.2      setosa
4             4.6          3.1           1.5          0.2      setosa
5             5.0          3.6           1.4          0.2      setosa
6             5.4          3.9           1.7          0.4      setosa
7             4.6          3.4           1.4          0.3      setosa
8             5.0          3.4           1.5          0.2      setosa
9             4.4          2.9           1.4          0.2      setosa
10            4.9          3.1           1.5          0.1      setosa
11            5.4          3.7           1.5          0.2      setosa
12            4.8          3.4           1.6          0.2      setosa
13            4.8          3.0           1.4          0.1      setosa
14            4.3          3.0           1.1          0.1      setosa
15            5.8          4.0           1.2          0.2      setosa
16            5.7          4.4           1.5          0.4      setosa
17            5.4          3.9           1.3          0.4      setosa
18            5.1          3.5           1.4          0.3      setosa
19            5.7          3.8           1.7          0.3      setosa
20            5.1          3.8           1.5          0.3      setosa
21            5.4          3.4           1.7          0.2      setosa
22            5.1          3.7           1.5          0.4      setosa
23            4.6          3.6           1.0          0.2      setosa
24            5.1          3.3           1.7          0.5      setosa
25            4.8          3.4           1.9          0.2      setosa
26            5.0          3.0           1.6          0.2      setosa
27            5.0          3.4           1.6          0.4      setosa
28            5.2          3.5           1.5          0.2      setosa
29            5.2          3.4           1.4          0.2      setosa
30            4.7          3.2           1.6          0.2      setosa
31            4.8          3.1           1.6          0.2      setosa
32            5.4          3.4           1.5          0.4      setosa
33            5.2          4.1           1.5          0.1      setosa
34            5.5          4.2           1.4          0.2      setosa
35            4.9          3.1           1.5          0.2      setosa
36            5.0          3.2           1.2          0.2      setosa
37            5.5          3.5           1.3          0.2      setosa
38            4.9          3.6           1.4          0.1      setosa
39            4.4          3.0           1.3          0.2      setosa
40            5.1          3.4           1.5          0.2      setosa
41            5.0          3.5           1.3          0.3      setosa
42            4.5          2.3           1.3          0.3      setosa
43            4.4          3.2           1.3          0.2      setosa
44            5.0          3.5           1.6          0.6      setosa
45            5.1          3.8           1.9          0.4      setosa
46            4.8          3.0           1.4          0.3      setosa
47            5.1          3.8           1.6          0.2      setosa
48            4.6          3.2           1.4          0.2      setosa
49            5.3          3.7           1.5          0.2      setosa
50            5.0          3.3           1.4          0.2      setosa
51            7.0          3.2           4.7          1.4  versicolor
52            6.4          3.2           4.5          1.5  versicolor
53            6.9          3.1           4.9          1.5  versicolor
54            5.5          2.3           4.0          1.3  versicolor
55            6.5          2.8           4.6          1.5  versicolor
56            5.7          2.8           4.5          1.3  versicolor
57            6

In [80]:
iris_df= data('iris')

In [81]:
iris_df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

### **Importando arquivo .csv**

### Fazendo upload do arquivo



In [82]:
from google.colab import files

files.upload()

ModuleNotFoundError: No module named 'google'

### Lendo o arquivo

In [ ]:
dados_bussab= pd.read_csv('dados-bussab-csv.csv', sep=';', encoding='latin1')
dados_bussab

Unnamed: 0 estado_civil    instrucao  nfilho  salario  idade  meses  \
0            1     solteiro  Fundamental     NaN     4.00     26      3   
1            2       casado  Fundamental     1.0     4.56     32     10   
2            3       casado  Fundamental     2.0     5.25     36      5   
3            4     solteiro        Médio     NaN     5.73     20     10   
4            5     solteiro  Fundamental     NaN     6.26     40      7   
5            6       casado  Fundamental     0.0     6.66     28      0   
6            7     solteiro  Fundamental     NaN     6.86     41      0   
7            8     solteiro  Fundamental     NaN     7.39     43      4   
8            9       casado        Médio     1.0     7.59     34     10   
9           10     solteiro        Médio     NaN     7.44     23      6   
10          11       casado        Médio     2.0     8.12     33      6   
11          12     solteiro  Fundamental     NaN     8.46     27     11   
12          13     solteiro        Médio     NaN     8.74     37      5   
13          14       casado  Fundamental     3.0     8.95     44      2   
14          15       casado        Médio     0.0     9.13     30      5   
15          16     solteiro        Médio     NaN     9.35     38      8   
16          17       casado        Médio     1.0     9.77     31      7   
17          18       casado  Fundamental     2.0     9.80     39      7   
18          19     solteiro     Superior     NaN    10.53     25      8   
19          20     solteiro        Médio     NaN    10.76     37      4   
20          21       casado        Médio     1.0    11.06     30      9   
21          22     solteiro        Médio     NaN    11.59     34      2   
22          23     solteiro  Fundamental     NaN    12.00     41      0   
23          24       casado     Superior     0.0    12.79     26      1   
24          25       casado        Médio     2.0    13.23     32      5   
25          26       casado        Médio     2.0    13.60     35      0   
26          27     solteiro  Fundamental     NaN    13.85     46      7   
27          28       casado        Médio     0.0    14.69     29      8   
28          29       casado        Médio     5.0    14.71     40      6   
29          30       casado        Médio     2.0    15.99     35     10   
30          31     solteiro     Superior     NaN    16.22     31      5   
31          32       casado        Médio     1.0    16.61     36      4   
32          33       casado     Superior     3.0    17.26     43      7   
33          34     solteiro     Superior     NaN    18.75     33      7   
34          35       casado        Médio     2.0    19.40     48     11   
35          36       casado     Superior     3.0    23.30     42      2   

      regiao  
0   interior  
1    capital  
2    capital  
3      outro  
4      outro  
5   interior  
6   interior  
7    capital  
8    capital  
9      outro  
10  interior  
11   capital  
12     outro  
13     outro  
14  interior  
15     outro  
16   capital  
17     outro  
18  interior  
19  interior  
20     outro  
21   capital  
22     outro  
23     outro  
24  interior  
25     outro  
26     outro  
27  interior  
28  interior  
29   capital  
30     outro  
31  interior  
32   capital  
33   capital  
34   capital  
35  interior

### **Importando arquivo .txt**

### Fazendo upload do arquivo

In [ ]:
from google.colab import files

files.upload()

Saving dados-bussab-txt.txt to dados-bussab-txt.txt


{'dados-bussab-txt.txt': b'\testado_civil\tinstrucao\tnfilho\tsalario\tidade\tmeses\tregiao\r\n1\tsolteiro\tFundamental\t\t4.00\t26\t3\tinterior\r\n2\tcasado\tFundamental\t1\t4.56\t32\t10\tcapital\r\n3\tcasado\tFundamental\t2\t5.25\t36\t5\tcapital\r\n4\tsolteiro\tM\xc3\xa9dio\t\t5.73\t20\t10\toutro\r\n5\tsolteiro\tFundamental\t\t6.26\t40\t7\toutro\r\n6\tcasado\tFundamental\t0\t6.66\t28\t0\tinterior\r\n7\tsolteiro\tFundamental\t\t6.86\t41\t0\tinterior\r\n8\tsolteiro\tFundamental\t\t7.39\t43\t4\tcapital\r\n9\tcasado\tM\xc3\xa9dio\t1\t7.59\t34\t10\tcapital\r\n10\tsolteiro\tM\xc3\xa9dio\t\t7.44\t23\t6\toutro\r\n11\tcasado\tM\xc3\xa9dio\t2\t8.12\t33\t6\tinterior\r\n12\tsolteiro\tFundamental\t\t8.46\t27\t11\tcapital\r\n13\tsolteiro\tM\xc3\xa9dio\t\t8.74\t37\t5\toutro\r\n14\tcasado\tFundamental\t3\t8.95\t44\t2\toutro\r\n15\tcasado\tM\xc3\xa9dio\t0\t9.13\t30\t5\tinterior\r\n16\tsolteiro\tM\xc3\xa9dio\t\t9.35\t38\t8\toutro\r\n17\tcasado\tM\xc3\xa9dio\t1\t9.77\t31\t7\tcapital\r\n18\tcasado\tFund

### Lendo o arquivo

In [ ]:
dados_bussab= pd.read_table('dados-bussab-txt.txt')
dados_bussab

Unnamed: 0 estado_civil    instrucao  nfilho  salario  idade  meses  \
0            1     solteiro  Fundamental     NaN     4.00     26      3   
1            2       casado  Fundamental     1.0     4.56     32     10   
2            3       casado  Fundamental     2.0     5.25     36      5   
3            4     solteiro        Médio     NaN     5.73     20     10   
4            5     solteiro  Fundamental     NaN     6.26     40      7   
5            6       casado  Fundamental     0.0     6.66     28      0   
6            7     solteiro  Fundamental     NaN     6.86     41      0   
7            8     solteiro  Fundamental     NaN     7.39     43      4   
8            9       casado        Médio     1.0     7.59     34     10   
9           10     solteiro        Médio     NaN     7.44     23      6   
10          11       casado        Médio     2.0     8.12     33      6   
11          12     solteiro  Fundamental     NaN     8.46     27     11   
12          13     solteiro        Médio     NaN     8.74     37      5   
13          14       casado  Fundamental     3.0     8.95     44      2   
14          15       casado        Médio     0.0     9.13     30      5   
15          16     solteiro        Médio     NaN     9.35     38      8   
16          17       casado        Médio     1.0     9.77     31      7   
17          18       casado  Fundamental     2.0     9.80     39      7   
18          19     solteiro     Superior     NaN    10.53     25      8   
19          20     solteiro        Médio     NaN    10.76     37      4   
20          21       casado        Médio     1.0    11.06     30      9   
21          22     solteiro        Médio     NaN    11.59     34      2   
22          23     solteiro  Fundamental     NaN    12.00     41      0   
23          24       casado     Superior     0.0    12.79     26      1   
24          25       casado        Médio     2.0    13.23     32      5   
25          26       casado        Médio     2.0    13.60     35      0   
26          27     solteiro  Fundamental     NaN    13.85     46      7   
27          28       casado        Médio     0.0    14.69     29      8   
28          29       casado        Médio     5.0    14.71     40      6   
29          30       casado        Médio     2.0    15.99     35     10   
30          31     solteiro     Superior     NaN    16.22     31      5   
31          32       casado        Médio     1.0    16.61     36      4   
32          33       casado     Superior     3.0    17.26     43      7   
33          34     solteiro     Superior     NaN    18.75     33      7   
34          35       casado        Médio     2.0    19.40     48     11   
35          36       casado     Superior     3.0    23.30     42      2   

      regiao  
0   interior  
1    capital  
2    capital  
3      outro  
4      outro  
5   interior  
6   interior  
7    capital  
8    capital  
9      outro  
10  interior  
11   capital  
12     outro  
13     outro  
14  interior  
15     outro  
16   capital  
17     outro  
18  interior  
19  interior  
20     outro  
21   capital  
22     outro  
23     outro  
24  interior  
25     outro  
26     outro  
27  interior  
28  interior  
29   capital  
30     outro  
31  interior  
32   capital  
33   capital  
34   capital  
35  interior

### **Importando arquivo .xlsx**

### Fazendo upload do arquivo

In [ ]:
from google.colab import files

files.upload()

Saving dados-bussab-excel.xlsx to dados-bussab-excel.xlsx


{'dados-bussab-excel.xlsx': b'PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00q\x0e9+p\x01\x00\x00\xa0\x05\x00\x00\x13\x00\xdb\x01[Content_Types].xml \xa2\xd7\x01(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x

### Lendo o arquivo

In [ ]:
dados_bussab= pd.read_excel('dados-bussab-excel.xlsx')
dados_bussab

Unnamed: 0 estado_civil    instrucao  nfilho  salario  idade  meses  \
0            1     solteiro  Fundamental     NaN     4.00     26      3   
1            2       casado  Fundamental     1.0     4.56     32     10   
2            3       casado  Fundamental     2.0     5.25     36      5   
3            4     solteiro        Médio     NaN     5.73     20     10   
4            5     solteiro  Fundamental     NaN     6.26     40      7   
5            6       casado  Fundamental     0.0     6.66     28      0   
6            7     solteiro  Fundamental     NaN     6.86     41      0   
7            8     solteiro  Fundamental     NaN     7.39     43      4   
8            9       casado        Médio     1.0     7.59     34     10   
9           10     solteiro        Médio     NaN     7.44     23      6   
10          11       casado        Médio     2.0     8.12     33      6   
11          12     solteiro  Fundamental     NaN     8.46     27     11   
12          13     solteiro        Médio     NaN     8.74     37      5   
13          14       casado  Fundamental     3.0     8.95     44      2   
14          15       casado        Médio     0.0     9.13     30      5   
15          16     solteiro        Médio     NaN     9.35     38      8   
16          17       casado        Médio     1.0     9.77     31      7   
17          18       casado  Fundamental     2.0     9.80     39      7   
18          19     solteiro     Superior     NaN    10.53     25      8   
19          20     solteiro        Médio     NaN    10.76     37      4   
20          21       casado        Médio     1.0    11.06     30      9   
21          22     solteiro        Médio     NaN    11.59     34      2   
22          23     solteiro  Fundamental     NaN    12.00     41      0   
23          24       casado     Superior     0.0    12.79     26      1   
24          25       casado        Médio     2.0    13.23     32      5   
25          26       casado        Médio     2.0    13.60     35      0   
26          27     solteiro  Fundamental     NaN    13.85     46      7   
27          28       casado        Médio     0.0    14.69     29      8   
28          29       casado        Médio     5.0    14.71     40      6   
29          30       casado        Médio     2.0    15.99     35     10   
30          31     solteiro     Superior     NaN    16.22     31      5   
31          32       casado        Médio     1.0    16.61     36      4   
32          33       casado     Superior     3.0    17.26     43      7   
33          34     solteiro     Superior     NaN    18.75     33      7   
34          35       casado        Médio     2.0    19.40     48     11   
35          36       casado     Superior     3.0    23.30     42      2   

      regiao  
0   interior  
1    capital  
2    capital  
3      outro  
4      outro  
5   interior  
6   interior  
7    capital  
8    capital  
9      outro  
10  interior  
11   capital  
12     outro  
13     outro  
14  interior  
15     outro  
16   capital  
17     outro  
18  interior  
19  interior  
20     outro  
21   capital  
22     outro  
23     outro  
24  interior  
25     outro  
26     outro  
27  interior  
28  interior  
29   capital  
30     outro  
31  interior  
32   capital  
33   capital  
34   capital  
35  interior

# **Visualizando o dataframe**

In [ ]:
# Exibe as primeiras linhas do conjunto de dados:
dados_bussab.head()

Unnamed: 0 estado_civil    instrucao  nfilho  salario  idade  meses  \
0           1     solteiro  Fundamental     NaN     4.00     26      3   
1           2       casado  Fundamental     1.0     4.56     32     10   
2           3       casado  Fundamental     2.0     5.25     36      5   
3           4     solteiro        Médio     NaN     5.73     20     10   
4           5     solteiro  Fundamental     NaN     6.26     40      7   

     regiao  
0  interior  
1   capital  
2   capital  
3     outro  
4     outro

In [ ]:
# Exibe as primeiras linhas do conjunto de dados (quantidade desejada de linhas):
dados_bussab.head(7)

Unnamed: 0 estado_civil    instrucao  nfilho  salario  idade  meses  \
0           1     solteiro  Fundamental     NaN     4.00     26      3   
1           2       casado  Fundamental     1.0     4.56     32     10   
2           3       casado  Fundamental     2.0     5.25     36      5   
3           4     solteiro        Médio     NaN     5.73     20     10   
4           5     solteiro  Fundamental     NaN     6.26     40      7   
5           6       casado  Fundamental     0.0     6.66     28      0   
6           7     solteiro  Fundamental     NaN     6.86     41      0   

     regiao  
0  interior  
1   capital  
2   capital  
3     outro  
4     outro  
5  interior  
6  interior

In [ ]:
# Exibe as últimas linhas do conjunto de dados:
dados_bussab.tail()

Unnamed: 0 estado_civil instrucao  nfilho  salario  idade  meses    regiao
31          32       casado     Médio     1.0    16.61     36      4  interior
32          33       casado  Superior     3.0    17.26     43      7   capital
33          34     solteiro  Superior     NaN    18.75     33      7   capital
34          35       casado     Médio     2.0    19.40     48     11   capital
35          36       casado  Superior     3.0    23.30     42      2  interior

In [ ]:
# dimensão do dataset:
dados_bussab.shape

(36, 8)

In [ ]:
# Digitando um dataframe no Python (pandas e numpy):
example_df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['a', 'b', 'c']
                          )
example_df

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
# Digitando um dataframe no Python (pandas):
example_df2 = pd.DataFrame([['João', 'Estatística', 20],
 ['Laura', 'Bach Matemática', 19],
  ['Pedro', 'Licenc Matemática', 19]],
                   columns=['Nome', 'Curso', 'Idade'])
example_df2

Nome              Curso  Idade
0   João        Estatística     20
1  Laura    Bach Matemática     19
2  Pedro  Licenc Matemática     19

In [ ]:
# Verificando as dimensões do dataframe:
example_df.shape

(3, 3)

In [ ]:
# Verficando tamanho (total de células) do dataframe:
example_df.size

9

In [ ]:
# Variáveis (colunas) do dataframe:
dados_bussab.columns

Index(['Unnamed: 0', 'estado_civil', 'instrucao', 'nfilho', 'salario', 'idade',
       'meses', 'regiao'],
      dtype='object')

In [ ]:
# Renomeando uma coluna:
dados_bussab.rename(columns={'Unnamed: 0' : 'Funcionário'}, inplace=True)
dados_bussab.head()

Funcionário estado_civil    instrucao  nfilho  salario  idade  meses  \
0            1     solteiro  Fundamental     NaN     4.00     26      3   
1            2       casado  Fundamental     1.0     4.56     32     10   
2            3       casado  Fundamental     2.0     5.25     36      5   
3            4     solteiro        Médio     NaN     5.73     20     10   
4            5     solteiro  Fundamental     NaN     6.26     40      7   

     regiao  
0  interior  
1   capital  
2   capital  
3     outro  
4     outro

In [ ]:
# Removendo uma coluna:
dados_bussab.drop('Funcionário', axis='columns', inplace=True)
dados_bussab.head()

estado_civil    instrucao  nfilho  salario  idade  meses    regiao
0     solteiro  Fundamental     NaN     4.00     26      3  interior
1       casado  Fundamental     1.0     4.56     32     10   capital
2       casado  Fundamental     2.0     5.25     36      5   capital
3     solteiro        Médio     NaN     5.73     20     10     outro
4     solteiro  Fundamental     NaN     6.26     40      7     outro

In [ ]:
# Resumo das informações do dataframe:
dados_bussab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   estado_civil  36 non-null     object 
 1   instrucao     36 non-null     object 
 2   nfilho        20 non-null     float64
 3   salario       36 non-null     float64
 4   idade         36 non-null     int64  
 5   meses         36 non-null     int64  
 6   regiao        36 non-null     object 
dtypes: float64(2), int64(2), object(3)
memory usage: 2.1+ KB


In [ ]:
## Mudando o tipo de uma variável (neste caso não funciona por causa dos valores ausentes):
dados_bussab['nfilho'].astype('int64')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
# Mudando o tipo de uma variável
dados_bussab['meses'].astype('float64')#.dtypes

0      3.0
1     10.0
2      5.0
3     10.0
4      7.0
5      0.0
6      0.0
7      4.0
8     10.0
9      6.0
10     6.0
11    11.0
12     5.0
13     2.0
14     5.0
15     8.0
16     7.0
17     7.0
18     8.0
19     4.0
20     9.0
21     2.0
22     0.0
23     1.0
24     5.0
25     0.0
26     7.0
27     8.0
28     6.0
29    10.0
30     5.0
31     4.0
32     7.0
33     7.0
34    11.0
35     2.0
Name: meses, dtype: float64

In [ ]:
dados_bussab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   estado_civil  36 non-null     object 
 1   instrucao     36 non-null     object 
 2   nfilho        20 non-null     float64
 3   salario       36 non-null     float64
 4   idade         36 non-null     int64  
 5   meses         36 non-null     int64  
 6   regiao        36 non-null     object 
dtypes: float64(2), int64(2), object(3)
memory usage: 2.1+ KB


In [ ]:
# Mudando o tipo de uma variável (tem que redefinir a variável para aplicar a mudança no dataframe)
dados_bussab['meses'] = dados_bussab['meses'].astype('float64')#.dtypes

In [ ]:
dados_bussab.head()

estado_civil    instrucao  nfilho  salario  idade  meses    regiao
0     solteiro  Fundamental     NaN     4.00     26    3.0  interior
1       casado  Fundamental     1.0     4.56     32   10.0   capital
2       casado  Fundamental     2.0     5.25     36    5.0   capital
3     solteiro        Médio     NaN     5.73     20   10.0     outro
4     solteiro  Fundamental     NaN     6.26     40    7.0     outro

In [ ]:
dados_bussab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   estado_civil  36 non-null     object 
 1   instrucao     36 non-null     object 
 2   nfilho        20 non-null     float64
 3   salario       36 non-null     float64
 4   idade         36 non-null     int64  
 5   meses         36 non-null     float64
 6   regiao        36 non-null     object 
dtypes: float64(3), int64(1), object(3)
memory usage: 2.1+ KB


In [ ]:
# Verificando quantos valores únicos para cada variável:
dados_bussab.nunique()

estado_civil     2
instrucao        3
nfilho           5
salario         36
idade           24
meses           12
regiao           3
dtype: int64

In [ ]:
# Verificando se há linhas duplicadas:
dados_bussab.duplicated().sum()

np.int64(0)

In [ ]:
# Verificando valores ausentes nas variáveis:
dados_bussab.isnull().sum()

estado_civil     0
instrucao        0
nfilho          16
salario          0
idade            0
meses            0
regiao           0
dtype: int64

In [ ]:
# Selecionando uma amostra aleatória:
dados_bussab.sample()

estado_civil    instrucao  nfilho  salario  idade  meses   regiao
11     solteiro  Fundamental     NaN     8.46     27   11.0  capital

In [ ]:
# Selecionando uma amostra aleatória (n=4):
dados_bussab.sample(4)

estado_civil    instrucao  nfilho  salario  idade  meses regiao
20       casado        Médio     1.0    11.06     30    9.0  outro
30     solteiro     Superior     NaN    16.22     31    5.0  outro
13       casado  Fundamental     3.0     8.95     44    2.0  outro
15     solteiro        Médio     NaN     9.35     38    8.0  outro

In [ ]:
# Selecionando uma amostra aleatória (n=4) - com semente (para reprodutibilidade)
dados_bussab.sample(4, random_state=2025)

estado_civil    instrucao  nfilho  salario  idade  meses    regiao
6      solteiro  Fundamental     NaN     6.86     41    0.0  interior
2        casado  Fundamental     2.0     5.25     36    5.0   capital
20       casado        Médio     1.0    11.06     30    9.0     outro
23       casado     Superior     0.0    12.79     26    1.0     outro

In [ ]:
# Acessando uma coluna específica do dataframe:
dados_bussab['estado_civil'].head()

0    solteiro
1      casado
2      casado
3    solteiro
4    solteiro
Name: estado_civil, dtype: object

In [ ]:
# Acessando mais de uma coluna do dataframe:
dados_bussab[['estado_civil','idade', 'regiao']].head()

estado_civil  idade    regiao
0     solteiro     26  interior
1       casado     32   capital
2       casado     36   capital
3     solteiro     20     outro
4     solteiro     40     outro

## **Exportando dataframes:**

### Opção 1: Exportando e fazendo o download

In [ ]:
example_df2

Nome              Curso  Idade
0   João        Estatística     20
1  Laura    Bach Matemática     19
2  Pedro  Licenc Matemática     19

In [ ]:
from google.colab import files

In [ ]:
# csv:
example_df2.to_csv('exemplo_exportar.csv', encoding='utf-8', index=False)  ## exporta
files.download('exemplo_exportar.csv')                                     ## faz o download

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# txt:
example_df2.to_string('exemplo_exportar.txt', index=False)  ## exporta
files.download('exemplo_exportar.txt')                      ## faz o download

In [ ]:
# excel:
example_df2.to_excel('exemplo_exportar.xlsx', index=False)  ## exporta
files.download('exemplo_exportar.xlsx')                     ## faz o download

### Opção 2: Exportando e salvando no Google Drive

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Criando uma pasta para os arquivos da aula:
import os

# Caminho da pasta dentro do Google Drive
pasta = "/content/drive/MyDrive/ProbEstatA_2025-2"

# Criando a pasta (caso não exista)
os.makedirs(pasta, exist_ok=True)

In [ ]:
# csv:
path = os.path.join(pasta, 'exemplo_exportar.csv')

with open(path, 'w', encoding = 'utf-8') as f:
  example_df2.to_csv(f)

In [ ]:
# txt:
path = os.path.join(pasta, 'exemplo_exportar.txt')

with open(path, 'w') as f:
  example_df2.to_string(f)

In [ ]:
# excel:
path = os.path.join(pasta, 'exemplo_exportar.xlsx')

with open(path, 'wb') as f:
  example_df2.to_excel(f)